version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Nothing to do in the pre build phase...
  build:
    commands: 
      - echo Build started on `date`
      #获取编译源码用的依赖库（自动获取）
      - npm install
      - echo npm run build completed on `date`
      #进行编译
      - npm run build
      - echo upm run build completed on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - ls -l ./dist/shop/
artifacts:
    files:
      - dist/shop/*
      - dist/shop/assets/*
<<<<<<< HEAD:buildspec.yaml
      - appspec.yml
=======
      - appsepc.yml
>>>>>>> 4e6d71a3768fd5ea2e195e28de1a434f478a4831:buildspec.yml
